################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

################ French language ##################
[fr]
languageName = "Fran√ßais"
languageCode = "fr-FR"
contentDir = "content/french"
weight = 2
disabled = true

################ Italian language #################
[it]
languageName = "Italiano"
languageCode = "it-IT"
contentDir = "content/italian"
weight = 3
disabled = true

################ German language ##################
[de]
languageName = "German"
languageCode = "de-at"
contentDir = "content/german"
weight = 4
disabled = true