################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

################ German language ##################
[de]
languageName = "Deutsch"
languageCode = "de-DE"
contentDir = "content/german"
weight = 2
disabled = false


################ French language ##################
[fr]
languageName = "Français"
languageCode = "fr-FR"
contentDir = "content/french"
weight = 3
disabled = true

################ Italian language #################
[it]
languageName = "Italiano"
languageCode = "it-IT"
contentDir = "content/italian"
weight = 4
disabled = true

################ Chinese language #################
[zh]
languageName = "中文"
languageCode = "zh-CN"
contentDir = "content/chinese"
weight = 5
disabled = false